version: '3.7'
services:
  fp_front: 
    container_name: fp_front
    build: 
      context: ./products/.
      dockerfile: Dockerfile 
    volumes:
      - './products:/opt/app'
      - './products/node_modules:/opt/app/node_modules'
    ports:
      - '3333:3000'
    environment:
      - NODE_ENV=development

  articles_front: 
    container_name: articles_front
    build: 
      context: ./articles/.
      dockerfile: Dockerfile 
    volumes:
      - './articles:/opt/app'
      - './articles/node_modules:/opt/app/node_modules'
    ports:
      - '3344:3000'
    environment:
      - NODE_ENV=development


