version: '3.7'
services:
  react_ctx_16_front: 
    container_name: react_ctx_16_front
    build: 
      context: ./users/.
      dockerfile: Dockerfile 
    volumes:
      - './users:/opt/app'
      - './users/node_modules:/opt/app/node_modules'
    ports:
      - '3360:3000'
    environment:
      - NODE_ENV=development

