version: '3.7'
services:
  react_context_2019: 
    container_name: react_context_2019
    build: 
      context: ./tasks/.
      dockerfile: Dockerfile 
    volumes:
      - './tasks:/opt/app'
      - './tasks/node_modules:/opt/app/node_modules'
    ports:
      - '3380:3000'
    environment:
      - NODE_ENV=development

