version: '3.7'
services:
  shopp_react_2019: 
    container_name: shopp_react_2019
    build: 
      context: ./shopping_react_2019/.
      dockerfile: Dockerfile 
    volumes:
      - './shopping_react_2019:/opt/app'
      - './shopping_react_2019/node_modules:/opt/app/node_modules'
    ports:
      - '3390:3000'
    environment:
      - NODE_ENV=development

